<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
		<string>pasmo</string>
	</array>
	<key>name</key>
	<string>Pasmo</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>;.*$</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\$[0-9a-fA-F]+\b</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.dec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\S+:</string>
			<key>name</key>
			<string>entity.name.label</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.source.pasmo</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.source.pasmo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(a|f|af|b|c|bc|d|e|de|h|l|hl|i|r|sp|ix|iy))\b</string>
			<key>name</key>
			<string>storage.type.register</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(adc|add|and|bit|call|ccf|cp|cpd|cpdr|cpi|cpir|cpl|daa|dec|di|djnz|ei|ex|exx|halt|im|in|inc|ind|indr|ini|inir|jp|jr|ld|ldd|ldr|ldi|ldir|neg|nop|or|otrd|otir|out|outd|outi|pop|push|res|ret|reti|retn|rl|rla|rlc|rlca|rld|rr|rra|rrc|rrca|rrd|rst|sbc|scf|set|sla|sra|srl|sub|xor))\b</string>
			<key>name</key>
			<string>keyword.mnemonic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(eq|ne|z|nz|po|pe))\b</string>
			<key>name</key>
			<string>keyword.mnemonic.condition</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(\.error|\.shift|\.warning|defb|defl|defm|defs|defw|ds|dw|else|end|endif|endm|endp|equ|exitm|if|include|incbin|irp|local|macro|org|proc|public|rept))\b</string>
			<key>name</key>
			<string>keyword.control.directive</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pasmo</string>
	<key>uuid</key>
	<string>4897bda1-ffd8-42f0-85e2-2044b6f0c95a</string>
</dict>
</plist>
